---
  - set_fact:
      install_from_source: true

  - set_fact:
      install_from_source: false
    when: >
      (slurm_version is version('23.11.0', '>=') and ansible_distribution_version >= "20.04") or
      (slurm_version == "23.02.6" and ansible_distribution_version == "24.04") or
      (slurm_version == "21.08.5" and ansible_distribution_version == "22.04") or
      (slurm_version == "19.05.5" and ansible_distribution_version == "20.04") or
      (slurm_version == "17.11.2" and ansible_distribution_version == "18.04")

  - name: Set default SLURM conf paths as facts
    set_fact:
      SLURM_CONF_DIR: "/etc/slurm"
      SLURM_SERVICE: "/usr/sbin/slurmctld"
      SLURM_DAEMON: "/usr/sbin/slurmd"

  # Add a fast check to speed reconfiguration
  - set_fact: SRUN_PATH=/usr/local/bin/srun
    when: ansible_os_family == "Debian" and install_from_source

  - set_fact: SRUN_PATH=/usr/bin/srun
    when: ansible_os_family == "RedHat" or not install_from_source

  - stat: path={{SRUN_PATH}}
    register: slurm_installed

  - name: Include "{{ansible_os_family}}" SLURM recipe
    include_tasks: "{{ansible_os_family}}.yaml"
    when: not slurm_installed.stat.exists

  - name: create slurm user and group
    user: name="{{slurm_user}}" shell=/bin/bash system=yes uid="{{ slurm_user_id }}"

  - name: create folders used by SLURM and set slurm owner
    file: path={{item}} state=directory owner=slurm group=slurm
    loop:
      - /var/spool/slurm
      - /var/log/slurm
      - /var/slurm/checkpoint
      - /etc/slurm

  - name: Use BLCR as checkpointing type
    set_fact:
      slurm_conf_options: "{{ slurm_default_conf_options | combine({'CheckpointType': 'checkpoint/blcr'}) }}"
    when : '"blcr" in templates'

  - name: Update default options with user options
    set_fact:
      slurm_conf_options: "{{ slurm_default_conf_options | combine(slurm_conf_options) }}"

  - name: Include "{{slurm_type_of_node}}" SLURM recipe
    include_tasks: "{{slurm_type_of_node}}.yaml"

  - name: Define the DRMAA library version as it does not work with SLURM 24
    set_fact:
      drmaa_lib_install: false
    when: slurm_version is version('24.0.0', '>=')

  - name: Install DRMAA Lib
    include_tasks: drmaa.yml
    when: drmaa_lib_install 
