---
  - set_fact:
      install_from_source: true

  - set_fact:
      install_from_source: false
    when: >
      (slurm_version == "21.08.5" and ansible_distribution_version == "22.04") or
      (slurm_version == "19.05.5" and ansible_distribution_version == "20.04") or
      (slurm_version == "17.11.2" and ansible_distribution_version == "18.04")

  # Add a fast check to speed reconfiguration
  - set_fact: SRUN_PATH=/usr/local/bin/srun
    when: ansible_os_family == "Debian" and install_from_source

  - set_fact: SRUN_PATH=/usr/bin/srun
    when: ansible_os_family == "RedHat" or not install_from_source

  - stat: path={{SRUN_PATH}}
    register: slurm_installed

  - name: Include "{{ansible_os_family}}" SLURM recipe
    include_tasks: "{{ansible_os_family}}.yaml"
    when: not slurm_installed.stat.exists

  - name: Set SLURM conf file path as fact RH
    set_fact:
      SLURM_CONF_DIR: "/etc/slurm"
      SLURM_SERVICE: "/usr/sbin/slurmctld"
      SLURM_DAEMON: "/usr/sbin/slurmd"
    when: ansible_os_family == "RedHat"

  - name: Set SLURM conf file path as fact Debian apt
    set_fact:
      SLURM_CONF_DIR: "/etc/slurm-llnl"
      SLURM_SERVICE: "/usr/sbin/slurmctld"
      SLURM_DAEMON: "/usr/sbin/slurmd"
    when: ansible_os_family == "Debian" and not install_from_source and slurm_version != "21.08.5"

  - name: Set SLURM conf file path as fact Debian apt with version 21.08.5
    set_fact:
      SLURM_CONF_DIR: "/etc/slurm"
      SLURM_SERVICE: "/usr/sbin/slurmctld"
      SLURM_DAEMON: "/usr/sbin/slurmd"
    when: ansible_os_family == "Debian" and not install_from_source and slurm_version == "21.08.5"

  - name: Set SLURM conf file path as fact Debian source
    set_fact:
      SLURM_CONF_DIR: "/usr/local/etc"
      SLURM_SERVICE: "/usr/local/sbin/slurmctld"
      SLURM_DAEMON: "/usr/local/sbin/slurmd"
    when: ansible_os_family == "Debian" and install_from_source

  - name: create slurm user and group
    user: name="{{slurm_user}}" shell=/bin/bash system=yes uid="{{ slurm_user_id }}"

  - name: create folders used by SLURM and set slurm owner
    file: path={{item}} state=directory owner=slurm group=slurm
    loop:
      - /var/spool/slurm
      - /var/log/slurm
      - /var/slurm/checkpoint
      - /etc/slurm

  - name: Use BLCR as checkpointing type
    set_fact:
      slurm_conf_options: "{{ slurm_default_conf_options | combine({'CheckpointType': 'checkpoint/blcr'}) }}"
    when : '"blcr" in templates'

  - name: Update default options with user options
    set_fact:
      slurm_conf_options: "{{ slurm_default_conf_options | combine(slurm_conf_options) }}"

  - name: Include "{{slurm_type_of_node}}" SLURM recipe
    include_tasks: "{{slurm_type_of_node}}.yaml"

  - name: Install DRMAA Lib
    include_tasks: drmaa.yml
    when: drmaa_lib_install 