---
  # Add a fast check to speed reconfiguration
  - set_fact: SRUN_PATH=/usr/local/bin/srun
    when: ansible_os_family == "Debian"

  - set_fact: SRUN_PATH=/usr/bin/srun
    when: ansible_os_family == "RedHat"

  - stat: path={{SRUN_PATH}}
    register: slurm_installed

  - name: Include "{{ansible_os_family}}" SLURM recipe
    include: "{{ansible_os_family}}.yaml"
    static: false
    when: not slurm_installed.stat.exists

  - name: Set SLURM conf file path as fact RH
    set_fact:
      SLURM_CONF: "/etc/slurm/slurm.conf"
      SLURM_SERVICE: "slurm"
      SLURM_DAEMON: "slurm"
    when: ansible_os_family == "RedHat"

  - name: Set SLURM conf file path as fact Debian
    set_fact:
      SLURM_CONF: "/usr/local/etc/slurm.conf"
      SLURM_SERVICE: "slurmctld"
      SLURM_DAEMON: "slurmd"
    when: ansible_os_family == "Debian"

  - name: create slurm user and group
    user: name="{{slurm_user}}" shell=/bin/bash system=yes uid="{{ slurm_user_id }}"

  - name: create folders used by SLURM and set slurm owner
    file: path={{item}} state=directory owner=slurm group=slurm
    with_items:
      - /var/spool/slurm
      - /var/log/slurm
      - /var/slurm/checkpoint
      - /etc/slurm

  - name: Include "{{slurm_type_of_node}}" SLURM recipe
    include: "{{slurm_type_of_node}}.yaml"

  - name: Install DRMAA Lib
    include: drmaa.yml
    when: drmaa_lib_install 