---
  #SLURM dependences
  - name: Install epel repo
    yum: name=epel-release,yum-priorities

  - name: Add GRyCAP Repo key
    rpm_key: state=present key="http://ftpgrycap.i3m.upv.es/centos/keyFile"

  - name: Add GRyCAP Repo
    get_url: url="http://ftpgrycap.i3m.upv.es/centos/{{ansible_distribution_major_version}}/grycap.repo" dest=/etc/yum.repos.d/grycap.repo

  - name: Install rpm slurm packages (common for versions 17.11 and beyond)
    yum:
      name:
        - "slurm-{{slurm_version}}"
        - "slurm-devel-{{slurm_version}}"
        - "slurm-openlava-{{slurm_version}}"
        - "slurm-pam_slurm-{{slurm_version}}"
        - "slurm-perlapi-{{slurm_version}}"
        - "slurm-slurmdbd-{{slurm_version}}"
        - "slurm-torque-{{slurm_version}}"
        - "slurm-slurmd-{{slurm_version}}"
        - "slurm-slurmctld-{{slurm_version}}"
        - "slurm-libpmi-{{slurm_version}}"
        - "slurm-example-configs-{{slurm_version}}"
        - "slurm-contribs-{{slurm_version}}"
      state: present
