---
- name: Converge
  hosts: all
  become: true
  vars:
    ntp_enabled: false

  tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: "Include grycap.slurm"
      include_role:
        name: "ansible-role-slurm"
      vars:
        slurm_wn_cpus: 2
        slurm_wn_mem: 1048576
        slurm_wn_gres: "gpu:tesla:2"
