---
- name: Converge
  hosts: all
  become: true

  tasks:

    - name: "Include grycap.slurm"
      include_role:
        name: "ansible-role-slurm"
      vars:
        slurm_wn_cpus: 2
        slurm_wn_mem: 1048576
        slurm_wn_gres: "gpu:tesla:2"
        slurm_server_name: instance
        slurm_wn_ips: ["127.0.0.1"]
        slurm_vnode_prefix: vnode-
        max_number_of_nodes: 1
        drmaa_lib_install: true
        drmaa_lib_version: 1.1.4
        slurm_version: 21.08.8

    - name: "Include grycap.slurm"
      include_role:
        name: "ansible-role-slurm"
      vars:
        slurm_type_of_node: wn
        slurm_wn_cpus: 2
        slurm_wn_mem: 1048576
        slurm_wn_gres: "gpu:tesla:2"
        slurm_server_name: instance
        slurm_wn_ips: ["127.0.0.1"]
        slurm_vnode_prefix: vnode-
        max_number_of_nodes: 1
        drmaa_lib_install: true
        drmaa_lib_version: 1.1.4
        slurm_version: 21.08.8

    - name: Test
      command: scontrol show nodes
      changed_when: False
