---
scenario:
  name: cluster
  test_sequence:
    - dependency
    - destroy
    - create
    - prepare
    - converge
    # - idempotence
    - verify
    - destroy
dependency:
  name: galaxy
driver:
  name: docker
verifier:
  name: ansible
platforms:
  - name: slurmserver
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - front
    networks:
      - name: "slurm"
    network_mode: "slurm"
    published_ports:
      - 6818/tcp
      - 6817/tcp
  - name: vnode-1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - wn
    networks:
      - name: "slurm"
    network_mode: "slurm"
    published_ports:
      - 6818/tcp
      - 6817/tcp
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    group_vars:
      front:
        slurm_type_of_node: "front"
      wn:
        slurm_type_of_node: "wn"
