---
- name: Verify
  hosts: all
  become: true

  tasks:

    - name: Test
      command: scontrol show nodes
      register: nodes

    - name: Check service running
      fail:
        msg: "Error getting node IDLE state"
      when: "'NodeName=vnode-1' not in nodes.stdout or 'State=IDLE' not in nodes.stdout" 

